;; UI
(setq inhibit-startup-message t)
(setq visible-bell t)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)
(set-fringe-mode 5)
(set-fringe-mode 5)

;; Backup
(defvar backup-path (expand-file-name "backup" "~/.cache/emacs"))
(unless (file-directory-p backup-path) (make-directory backup-path t))
(setq make-backup-files t)
(setq backup-directory-alist `(("." . ,backup-path)))
(setq tramp-backup-directory-alist backup-directory-alist)
(setq backup-by-copying t)
(setq backup-by-copying-when-linked t)
(setq version-control t)
(setq kept-old-versions 2)
(setq kept-new-versions 2)
(setq delete-old-versions t)
(setq vc-make-backup-files nil)
(setq create-lockfiles nil)
